apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-api-service
  name: xelerate
spec:
  selector:
    name: app-api-service 
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
